[database]
mongodb_uri = "mongodb://localhost:27017"
database_name = "export_master_pro"
connection_timeout = 10
max_pool_size = 10

[redis]
redis_uri = "redis://localhost:6379"
connection_timeout = 5
max_connections = 10
default_ttl = 3600

[security]
encryption_key = "your-32-byte-encryption-key-here"
salt = "your-salt-here"
session_timeout = 86400

[backup]
backup_directory = "./backups"
backup_interval_hours = 24
max_backup_files = 30
compression_enabled = true

[logging]
level = "info"
file_path = "./logs/app.log"
max_file_size = 10485760
max_files = 5